CardGame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('trading/', include('trading.urls')),
    path('forum/', include('forum.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ForumListView.as_view(), name='forum'),
    path('newPost/', views.ThreadCreateView.as_view(), name='new_thread'),
    path('comment/create/<int:thread_id>/', views.CommentCreateView.as_view(), name='new_comment'),
    path('newPost/<int:pk>', views.ThreadDetailView.as_view(), name='view_post'),
    path('<int:pk>/deleteThread/', views.DeleteThread.as_view(), name='delete_thread'),

]

trading/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('allCards/', views.CardListView.as_view(), name='all_cards'),
    path('myDeck/', views.MyCardListView.as_view(), name='my_deck'),
    path('transactions/', views.TransactionView.as_view(), name='transactions'),
    path('transactions/<int:card_id>/', views.start_transaction, name='start_transaction'),
    path('transactions/remove/<int:transaction_id>/', views.remove_my_transaction, name='remove_transaction'),
    path('transactions/makeOffer/<int:transaction_id>/', views.OfferCreateView.as_view(), name='new_offer'),
    path('transactions/viewOffer/<int:pk>/', views.OfferView.as_view(), name='all_offers'),
    path('transactions/viewOffer/<int:offer_id>/<int:accepted>', views.transaction_action, name='action'),
    path('<int:pk>/deleteCard/', views.DeleteCard.as_view(), name='delete_card'),
    path('allCards/newCard/', views.CardCreateView.as_view(), name='new_card')
]

trading/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from accounts.models import Profile, User
from django.db import models
from django.conf import settings

import random


class Card(models.Model):
    card_id = models.PositiveIntegerField()
    name = models.CharField(max_length=50)
    rarity = models.PositiveIntegerField(default=0)
    image = models.URLField()


    def __str__(self):
        return self.name


class Deck(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    card = models.ManyToManyField(Card)


class Transaction(models.Model):
    STATUS = [('S', 'Start'), ('E', 'End')]
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    user_sell = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=STATUS, default='S', max_length=30)


class Offer(models.Model):
    STATUS = [('A', 'Accepted'), ('P', 'Pending'), ('R', 'Refused')]
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    buyer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, default='P', max_length=30)



# @receiver(post_save, sender=User)
# def my_callback(sender, instance, created, **kwargs):
#     if created:
#         prof = Profile.objects.create(user=instance)
#
#         cards = Card.objects.all().order_by('rarity')
#         num = cards.count() / 10
#         decks = random.sample(list(cards[0:num]), k=1) + random.sample(list(cards[num:num * 3]), k=3) + random.sample(list(cards[num * 3:num * 6]), k=15) + random.sample(list(cards[num * 6:num * 10]), k=30)
#
#         deck = Deck.objects.create(user=prof)
#         deck.card.add(*decks)

trading/forms.py
from django import forms
from .models import *


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['card']


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = '__all__'

trading/views.py
from django.shortcuts import render, redirect
from .models import Card, Transaction, Deck, Offer
from django.views.generic import CreateView, UpdateView, DetailView, ListView, View, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .forms import OfferForm, CardForm
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages


# Create your views here.

def homepage(request):
    return render(request, 'homepage.html')

class CardListView(ListView):
    model = Card
    template_name = 'all_cards.html'
    context_object_name = 'cards'


class MyCardListView(LoginRequiredMixin,ListView):
    model = Card
    template_name = 'my_deck.html'


class TransactionView(ListView, LoginRequiredMixin):
    model = Transaction
    template_name = 'transactions.html'
    context_object_name = 'transactions'

    def get_queryset(self):
        return super(TransactionView, self).get_queryset().filter(status='S')


@login_required
def start_transaction(request, card_id):
    new_transaction = Transaction.objects.create(card=Card.objects.get(id=card_id), user_sell=request.user.profile, status='S')
    deck = Deck.objects.get(user=request.user.profile)
    deck.card.remove(Card.objects.get(id=card_id))
    return redirect('transactions')


@login_required
def remove_my_transaction(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    transaction.status = 'E'
    transaction.save()
    deck = Deck.objects.get(user=request.user.profile)
    deck.card.add(transaction.card)
    return redirect('transactions')


class OfferCreateView(LoginRequiredMixin, CreateView):
    template_name = 'new_offer.html'
    success_url = reverse_lazy('transactions')
    model = Offer
    form_class = OfferForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.card in self.request.user.profile.deck.card.all():
            self.object.buyer = self.request.user.profile
            transaction_id = self.kwargs['transaction_id']
            transaction = Transaction.objects.get(id=transaction_id)
            self.object.transaction = transaction
            self.object = form.save()
            return HttpResponseRedirect(self.get_success_url())
        return render(self.request, 'not_have.html')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['card'].queryset = self.request.user.profile.deck.card.all()
        return form



class OfferView(LoginRequiredMixin, DetailView):
    model = Transaction
    template_name = 'all_offers.html'
    context = Offer

@login_required
def transaction_action(request, offer_id, accepted):
    offer = Offer.objects.get(id=offer_id)
    transaction = offer.transaction
    deck_seller = Deck.objects.get(user=transaction.user_sell)
    deck_buyer = Deck.objects.get(user=offer.buyer)
    if accepted:
        offer.status = 'A'
        transaction.status = 'E'
        offer.save()
        transaction.save()
        deck_buyer.card.add(transaction.card)
        deck_seller.card.add(offer.card)
        deck_buyer.card.remove(offer.card)
        return redirect('transactions')
    else:
        offer.status = 'R'
        offer.save()
        return redirect('all_offers', transaction.id)


class DeleteCard(DeleteView, UserPassesTestMixin):
    model = Card
    template_name = 'delete_view.html'
    success_url = reverse_lazy('all_cards')
    success_message = "The card was deleted successfully"

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message  % obj.__dict__)
        return super(DeleteCard, self).delete(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_staff


class CardCreateView(CreateView, UserPassesTestMixin):
    template_name = 'new_card.html'
    success_url = reverse_lazy('all_cards')
    model = Card
    form_class = CardForm

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def test_func(self):
        return self.request.user.is_staff

trading/templates/all_cards.html
{% extends 'partials/base.html'%}
{%block title%}
Cards
{% endblock%}
{% block content%}
{%if messages%}
{%for message in messages%}
<div class="alert alert-warning">{{message}}<br></div>
{%endfor%}
{%endif%}
<div class="container">
<h1 class="pt-3 ps-3 d-flex justify-content-evenly">All the cards</h1>
  {% if user.is_staff%}
  <a href="{% url 'new_card' %}" class="btn btn-danger">Add a new card</a>
  {% endif%}
  <div class="row d-flex justify-content-evenly ">
{%for card in cards%}

<div class="card mt-3" style="width: 18rem;">
  <img src="{{card.image}}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{card.name.upper}} #{{card.card_id}}</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">rarity: {{card.rarity}}</li>
    {% if user.is_staff%}
    <li class="list-group-item"><a href="{% url 'delete_card' card.id%}">delete card</a></li>
    {% endif%}
  </ul>
</div>

{% endfor %}
</div>

</div>
{% endblock %}

trading/templates/all_offers.html
{% extends 'partials/base.html'%}
{%block title%}
Offers
{% endblock%}
{% block content%}
<div class="container">
<div class="row">
<h1 class="pt-3 ps-3 d-flex justify-content-evenly">All the offers for {{transaction.card.name.upper}}</h1>
  <div class="row d-flex justify-content-evenly ">

<div class="card mt-3" style="width: 18rem;">
  <img src="{{transaction.card.image}}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{transaction.card.name.upper}} #{{transaction.card.card_id}}</h5>
    <p class="card-text">Seller: {{transaction.user_sell.user.username}} </p>
    <p class="card-text"> since {{transaction.timestamp | timesince}} ago</p>
  </div>
</div>
    <p><hr></p>
</div>


{%for offer in transaction.offer_set.all%}
{% if offer.status == 'P'%}

<div class="card mt-3" style="width: 18rem;">
  <img src="{{offer.card.image}}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{offer.card.name.upper}} #{{offer.card.card_id}}</h5>
    <p class="card-text">Offered by {{offer.buyer.user.username}}</p>
    <a href="{% url 'action' offer.id 1 %}" class="btn btn-success">Accepted</a>
    <a href="{% url 'action' offer.id 0 %}" class="btn btn-danger">Rejected</a>
  </div>
</div>
{%endif%}
{% endfor %}
</div>

</div>
{% endblock %}

trading/templates/homepage.html
{% extends 'partials/base.html'%}
{% load bootstrap5 %}
{% block content%}
<div class="container ">
    <h1 class="d-flex justify-content-center">{% if user.is_authenticated %} {{user.username}} {%endif%} Welcome to the Game Card</h1>
<br>
 {% if not user.is_authenticated %}
<h2 class="d-flex justify-content-center">If you want to play, you have to</h2>
<h2 class="d-flex justify-content-center"> <a href="{% url 'login'%}" class="btn btn-warning"> Login </a>  or  <a href="{% url 'signup'%}" class="btn btn-danger" > Signup </a> </h2>
{%endif%}
<div class="text-center mt-5">
<img class="img-fluid rounded mx-auto d-block" src="https://d3fa68hw0m2vcc.cloudfront.net/507/251047953.jpeg">
</div>
</div>
{% endblock %}

trading/templates/my_deck.html
{% extends 'partials/base.html'%}
{%block title%}
Cards
{% endblock%}
{% block content%}
<div class="container">
<h1 class="pt-3 ps-3 d-flex justify-content-evenly">My Deck</h1>
  <div class="row d-flex justify-content-evenly ">
{%for object in user.profile.deck.card.all%}


<div class="card mt-3" style="width: 18rem;">
  <img src="{{object.image}}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{object.name.upper}} #{{object.card_id}}</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">rarity: {{object.rarity}}</li>
  </ul>
    <a href="{% url 'start_transaction' object.card_id %}" class="card-link d-flex flex-column btn btn-warning">Sell the card</a>
</div>

{% endfor %}
</div>

</div>
{% endblock %}

trading/templates/new_card.html
{% extends 'partials/base.html' %}
{% load bootstrap5 %}
{% block title %}
Add a new Card
{% endblock %}

{% block content %}

<div class="container me-5 ms-5  ">
    <h1 class="d-flex justify-content-center">Create a new Card</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Add" button_type="submit" button_class="btn-success" %}
    </form>
</div>
{% endblock %}

trading/templates/new_offer.html
{% extends 'partials/base.html' %}
{% load bootstrap5 %}
{% block title %}
Make an offer
{% endblock %}

{% block content %}

<div class="container me-5 ms-5  ">
    <h1 class="d-flex justify-content-center">Make an Offer</h1>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Make an offer" button_type="submit" button_class="btn-success" %}
    </form>
</div>
{% endblock %}

trading/templates/not_have.html
{% extends 'partials/base.html'%}
{%block title%}
Error
{% endblock%}
{% block content%}
<h2>You don't have this card in your desk</h2>
<a href="{% url 'transactions'%}" class="btn btn-warning">Make another transaction</a>
<a href="{% url 'my_deck'%}" class="btn btn-warning">Go back to my deck</a>
{% endblock %}

trading/templates/transactions.html
{% extends 'partials/base.html'%}
{%block title%}
Cards
{% endblock%}
{% block content%}
<div class="container">
<h1 class="pt-3 ps-3 d-flex justify-content-evenly">All the Transactions</h1>
  <div class="row d-flex justify-content-evenly ">

{%for transaction in transactions%}
{% if transaction.status == 'S'%}

<div class="card mt-3" style="width: 18rem;">
  <img src="{{transaction.card.image}}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{transaction.card.name.upper}} #{{transaction.card.card_id}}</h5>
    <p class="card-text">Seller: <a href="{%url 'profile' transaction.user_sell.user.id%}">{{transaction.user_sell.user.username}}</a></p>
    <p class="card-text"> since {{transaction.timestamp | timesince}} ago</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">rarity: {{transaction.card.rarity}}</li>
    {% if user.profile == transaction.user_sell%}
    <a href="{% url 'remove_transaction' transaction.id %}">remove card from transactions</a>
    {%endif%}
  </ul>
  {% if not user.profile == transaction.user_sell%}
  <a href="{% url 'new_offer' transaction.id %}" class="card-link d-flex flex-column btn btn-danger">Make an offer</a>
  {% else %}
  <a href="{% url 'all_offers' transaction.id%}" class="card-link d-flex flex-column btn btn-warning">View offers</a>
  {% endif %}
</div>
{%endif%}
{% endfor %}
</div>

</div>
{% endblock %}